name: Update dependencies

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: current
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: cargo install cargo-edit cargo-audit
    - run: cd src/test/rust/simulator && cargo upgrade && cargo update && cargo audit
    - run: cd src/main/rust/cardtool && cargo upgrade && cargo update && cargo audit
    # NOTE: checkstyle version is fixed in build.gradle
    - run: gradle dependencies --write-locks
    - run: gradle --write-verification-metadata sha512 help
    # dockerimage.yml is not triggered without repo scoped token, doing testing in the task, ref. https://github.com/peter-evans/create-pull-request/issues/48
    - run: gradle build auditSimulatorLibrary
    - run: gradle -Pjc_version=3.0.5 --console=verbose clean cap --info
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      title: Update dependencies
      commit-message: Update dependencies
      delete-branch: true
